' @startsalt
' {
'   {^
'     <b>FastDelivery - Buscar Restaurantes</b>
'   }
'   {
'     [🔍 Buscar...] | [Filtros ▼]
'   }
'   {
'     (X) Restaurante A      | ⭐ 4.5
'     () Restaurante B      | ⭐ 4.2
'     () Restaurante C      | ⭐ 4.7
'   }
'   {
'     [Ver Cardápio] | [Voltar]
'   }
' }
' @endsalt
' @startsalt
' {
'   {^
'     <b>Restaurante A - Cardápio</b>
'   }
'   {
'     (X) Pizza Margherita   | R$ 35.00
'     () Hambúrguer Artesanal | R$ 28.00
'     () Salada Caesar       | R$ 22.00
'   }
'   {
'     [Adicionar ao Carrinho] | [Voltar]
'   }
' }
' @endsalt
' @startsalt
' {
'   {^
'     <b>Carrinho de Compras</b>
'   }
'   {
'     "Pizza Margherita"  | R$ 35.00
'     "Hambúrguer"       | R$ 28.00
'     "Taxa de Entrega"  | R$ 5.00
'     --------------------------
'     "Total"            | R$ 68.00
'   }
'   {
'     [Continuar para Pagamento] | [Editar]
'   }
' }
' @endsalt
' @startsalt
' {
'   {^
'     <b>Pagamento</b>
'   }
'   {
'     () Cartão Crédito (•••• 1234)
'     () PIX
'     () Dinheiro na Entrega
'   }
'   {
'     [Finalizar Pedido] | [Cancelar]
'   }
' }
' @endsalt
' @startsalt
' {
'   {^
'     <b>Pedido Confirmado!</b>
'   }
'   {
'     ! Pedido #1234 recebido!
'     "Tempo estimado:" 30-40 min.
'   }
'   {
'     [Acompanhar Pedido] | [Voltar ao Início]
'   }
' }
' @endsalt