# Generated by Django 5.2.2 on 2025-06-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censo', '0007_remove_domicilio_distrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='num_casa',
            field=models.TextField(),
        ),
    ]
